# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.maplink_api import MaplinkApi


class TestMaplinkApi(unittest.TestCase):
    """MaplinkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MaplinkApi()

    def tearDown(self) -> None:
        pass

    def test_api_maplink_resolve_create(self) -> None:
        """Test case for api_maplink_resolve_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
