# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ev_info_updating import EVInfoUpdating

class TestEVInfoUpdating(unittest.TestCase):
    """EVInfoUpdating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EVInfoUpdating:
        """Test EVInfoUpdating
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EVInfoUpdating`
        """
        model = EVInfoUpdating()
        if include_optional:
            return EVInfoUpdating(
                force_soc_display = True
            )
        else:
            return EVInfoUpdating(
        )
        """

    def testEVInfoUpdating(self):
        """Test EVInfoUpdating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
