# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.map_link_resolver_response import MapLinkResolverResponse

class TestMapLinkResolverResponse(unittest.TestCase):
    """MapLinkResolverResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapLinkResolverResponse:
        """Test MapLinkResolverResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapLinkResolverResponse`
        """
        model = MapLinkResolverResponse()
        if include_optional:
            return MapLinkResolverResponse(
                status = True,
                cause = '0',
                location = openapi_client.models.map_link_resolved_location.MapLinkResolvedLocation(
                    lat = '', 
                    lon = '', 
                    name = '0', 
                    address = '0', )
            )
        else:
            return MapLinkResolverResponse(
                status = True,
        )
        """

    def testMapLinkResolverResponse(self):
        """Test MapLinkResolverResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
