# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.api.maplink_api import MaplinkApi


class TestMaplinkApi(unittest.IsolatedAsyncioTestCase):
    """MaplinkApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MaplinkApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_maplink_resolve_create(self) -> None:
        """Test case for api_maplink_resolve_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
