# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.api_command_create_request import ApiCommandCreateRequest

class TestApiCommandCreateRequest(unittest.TestCase):
    """ApiCommandCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiCommandCreateRequest:
        """Test ApiCommandCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiCommandCreateRequest`
        """
        model = ApiCommandCreateRequest()
        if include_optional:
            return ApiCommandCreateRequest(
                command_type = 1.337,
                command_payload = None,
                command_pin = ''
            )
        else:
            return ApiCommandCreateRequest(
                command_type = 1.337,
        )
        """

    def testApiCommandCreateRequest(self):
        """Test ApiCommandCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
