# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.token_api import TokenApi


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokenApi()

    def tearDown(self) -> None:
        pass

    def test_api_token_obtain_create(self) -> None:
        """Test case for api_token_obtain_create

        """
        pass

    def test_api_token_refresh_create(self) -> None:
        """Test case for api_token_refresh_create

        """
        pass

    def test_api_token_signout_create(self) -> None:
        """Test case for api_token_signout_create

        """
        pass

    def test_api_token_update_create(self) -> None:
        """Test case for api_token_update_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
