# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.tcu_configuration import TCUConfiguration

class TestTCUConfiguration(unittest.TestCase):
    """TCUConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TCUConfiguration:
        """Test TCUConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TCUConfiguration`
        """
        model = TCUConfiguration()
        if include_optional:
            return TCUConfiguration(
                id = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                dial_code = '',
                apn = '',
                apn_user = '',
                apn_password = '',
                dns1 = '',
                dns2 = '',
                server_url = '',
                proxy_url = '',
                connection_type = '',
                ficosa_config = opencarwings_client.models.ficosa_config.Ficosa config()
            )
        else:
            return TCUConfiguration(
        )
        """

    def testTCUConfiguration(self):
        """Test TCUConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
