# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.token_metadata_update import TokenMetadataUpdate

class TestTokenMetadataUpdate(unittest.TestCase):
    """TokenMetadataUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenMetadataUpdate:
        """Test TokenMetadataUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenMetadataUpdate`
        """
        model = TokenMetadataUpdate()
        if include_optional:
            return TokenMetadataUpdate(
                refresh = '0',
                device_type = '',
                device_os = '',
                app_version = '',
                push_notification_key = ''
            )
        else:
            return TokenMetadataUpdate(
                refresh = '0',
        )
        """

    def testTokenMetadataUpdate(self):
        """Test TokenMetadataUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
