# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.send_to_car_location import SendToCarLocation

class TestSendToCarLocation(unittest.TestCase):
    """SendToCarLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendToCarLocation:
        """Test SendToCarLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendToCarLocation`
        """
        model = SendToCarLocation()
        if include_optional:
            return SendToCarLocation(
                id = 56,
                lat = '',
                lon = '',
                name = '0',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SendToCarLocation(
                lat = '',
                lon = '',
                name = '0',
        )
        """

    def testSendToCarLocation(self):
        """Test SendToCarLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
