# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.command_timer_setting import CommandTimerSetting

class TestCommandTimerSetting(unittest.TestCase):
    """CommandTimerSetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommandTimerSetting:
        """Test CommandTimerSetting
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommandTimerSetting`
        """
        model = CommandTimerSetting()
        if include_optional:
            return CommandTimerSetting(
                id = 56,
                command_type_display = '',
                last_command_result_display = '',
                timer_type_display = '',
                last_command_execution = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enabled = True,
                name = '0',
                timer_type = 56,
                command_type = 56,
                last_command_result = 56,
                weekday_mon = True,
                weekday_tue = True,
                weekday_wed = True,
                weekday_thu = True,
                weekday_fri = True,
                weekday_sat = True,
                weekday_sun = True,
                time = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return CommandTimerSetting(
                name = '0',
                time = '',
        )
        """

    def testCommandTimerSetting(self):
        """Test CommandTimerSetting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
