# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pin_change import PinChange

class TestPinChange(unittest.TestCase):
    """PinChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PinChange:
        """Test PinChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PinChange`
        """
        model = PinChange()
        if include_optional:
            return PinChange(
                otp_code = '048072',
                old_pin = '04800',
                new_pin = '04800',
                new_pin_confirm = '04800'
            )
        else:
            return PinChange(
                new_pin = '04800',
                new_pin_confirm = '04800',
        )
        """

    def testPinChange(self):
        """Test PinChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
