# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_account_detail_list(self) -> None:
        """Test case for account_detail_list

        """
        pass

    def test_account_pin_create(self) -> None:
        """Test case for account_pin_create

        """
        pass

    def test_account_reset_api_key_create(self) -> None:
        """Test case for account_reset_api_key_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
