# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.car import Car

class TestCar(unittest.TestCase):
    """Car unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Car:
        """Test Car
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Car`
        """
        model = Car()
        if include_optional:
            return Car(
                id = 56,
                tcu_configuration = opencarwings_client.models.tcu_configuration.TCUConfiguration(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dial_code = '', 
                    apn = '', 
                    apn_user = '', 
                    apn_password = '', 
                    dns1 = '', 
                    dns2 = '', 
                    server_url = '', 
                    proxy_url = '', 
                    connection_type = '', 
                    ficosa_config = opencarwings_client.models.ficosa_config.Ficosa config(), ),
                location = opencarwings_client.models.location_info.LocationInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    lat = '', 
                    lon = '', 
                    home = True, ),
                ev_info = opencarwings_client.models.ev_info.EVInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    range_acon = -2147483648, 
                    range_acoff = -2147483648, 
                    plugged_in = True, 
                    charging = True, 
                    charge_finish = True, 
                    quick_charging = True, 
                    ac_status = True, 
                    charge_bars = -2147483648, 
                    car_running = True, 
                    car_gear = 56, 
                    eco_mode = True, 
                    soh = -2147483648, 
                    soc = 1.337, 
                    soc_display = 1.337, 
                    wh_content = 1.337, 
                    cap_bars = -2147483648, 
                    gids = -2147483648, 
                    counter = -2147483648, 
                    max_gids = -2147483648, 
                    full_chg_time = -2147483648, 
                    limit_chg_time = -2147483648, 
                    obc_6kw = -2147483648, 
                    param21 = -2147483648, 
                    cabin_temp = 1.337, 
                    force_soc_display = True, 
                    obc_6kw_avail = True, 
                    batt_heater_avail = True, 
                    batt_heater_status = True, ),
                veh_health = opencarwings_client.models.vehicle_health_info.VehicleHealthInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dtc_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dtc_short = opencarwings_client.models.dtc_short.Dtc short(), 
                    dtc_long = opencarwings_client.models.dtc_long.Dtc long(), 
                    tpms_light = True, 
                    tpms_fr = -2147483648, 
                    tpms_fl = -2147483648, 
                    tpms_rr = -2147483648, 
                    tpms_rl = -2147483648, 
                    maintenance_alert = True, 
                    mileage = 1.337, ),
                send_to_car_location_all = [
                    opencarwings_client.models.send_to_car_location.SendToCarLocation(
                        id = 56, 
                        lat = '', 
                        lon = '', 
                        name = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                send_to_car_location = opencarwings_client.models.send_to_car_location.SendToCarLocation(
                    id = 56, 
                    lat = '', 
                    lon = '', 
                    name = '0', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                route_plans = [
                    opencarwings_client.models.route_plan.RoutePlan(
                        id = 56, 
                        name = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        start_name = '0', 
                        start_lat = '', 
                        start_lon = '', 
                        finish_name = '0', 
                        finish_lat = '', 
                        finish_lon = '', 
                        point1_name = '', 
                        point1_lat = '', 
                        point1_lon = '', 
                        point2_name = '', 
                        point2_lat = '', 
                        point2_lon = '', 
                        point3_name = '', 
                        point3_lat = '', 
                        point3_lon = '', 
                        point4_name = '', 
                        point4_lat = '', 
                        point4_lon = '', 
                        point5_name = '', 
                        point5_lat = '', 
                        point5_lon = '', )
                    ],
                command_type_display = '0',
                command_result_display = '0',
                timer_commands = [
                    opencarwings_client.models.command_timer_setting.CommandTimerSetting(
                        id = 56, 
                        command_type_display = '', 
                        last_command_result_display = '', 
                        timer_type_display = '', 
                        last_command_execution = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        enabled = True, 
                        name = '0', 
                        timer_type = 56, 
                        command_type = 56, 
                        last_command_result = 56, 
                        weekday_mon = True, 
                        weekday_tue = True, 
                        weekday_wed = True, 
                        weekday_thu = True, 
                        weekday_fri = True, 
                        weekday_sat = True, 
                        weekday_sun = True, 
                        time = '', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                command_request_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_connection = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                supported_commands = [
                    56
                    ],
                sensitive_commands = [
                    56
                    ],
                command_pin_enforced = True,
                vin = '0',
                nickname = '0',
                sms_config = opencarwings_client.models.sms_config.Sms config(),
                color = 'l_coulisred',
                vehicle_code1 = -2147483648,
                vehicle_code2 = -2147483648,
                vehicle_code3 = -2147483648,
                vehicle_code4 = -2147483648,
                tcu_model = '0',
                tcu_serial = '0',
                iccid = '0',
                tcu_ver = '',
                tcu_user = '',
                tcu_pass = '',
                disable_auth = True,
                periodic_refresh = 56,
                periodic_refresh_running = 56,
                command_id = -2147483648,
                command_result = 56,
                command_requested = True,
                command_payload = opencarwings_client.models.command_payload.Command payload(),
                command_type = 56,
                carrier = '0',
                signal_level = -2147483648,
                odometer = -2147483648,
                navi_version = '',
                map_version = '',
                tcu_version = '',
                favorite_channels = opencarwings_client.models.favorite_channels.Favorite channels(),
                custom_channels = opencarwings_client.models.custom_channels.Custom channels(),
                hmac_key = '',
                tcu_type = 'continental2012',
                owner = 56
            )
        else:
            return Car(
                tcu_configuration = opencarwings_client.models.tcu_configuration.TCUConfiguration(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dial_code = '', 
                    apn = '', 
                    apn_user = '', 
                    apn_password = '', 
                    dns1 = '', 
                    dns2 = '', 
                    server_url = '', 
                    proxy_url = '', 
                    connection_type = '', 
                    ficosa_config = opencarwings_client.models.ficosa_config.Ficosa config(), ),
                location = opencarwings_client.models.location_info.LocationInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    lat = '', 
                    lon = '', 
                    home = True, ),
                ev_info = opencarwings_client.models.ev_info.EVInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    range_acon = -2147483648, 
                    range_acoff = -2147483648, 
                    plugged_in = True, 
                    charging = True, 
                    charge_finish = True, 
                    quick_charging = True, 
                    ac_status = True, 
                    charge_bars = -2147483648, 
                    car_running = True, 
                    car_gear = 56, 
                    eco_mode = True, 
                    soh = -2147483648, 
                    soc = 1.337, 
                    soc_display = 1.337, 
                    wh_content = 1.337, 
                    cap_bars = -2147483648, 
                    gids = -2147483648, 
                    counter = -2147483648, 
                    max_gids = -2147483648, 
                    full_chg_time = -2147483648, 
                    limit_chg_time = -2147483648, 
                    obc_6kw = -2147483648, 
                    param21 = -2147483648, 
                    cabin_temp = 1.337, 
                    force_soc_display = True, 
                    obc_6kw_avail = True, 
                    batt_heater_avail = True, 
                    batt_heater_status = True, ),
                send_to_car_location_all = [
                    opencarwings_client.models.send_to_car_location.SendToCarLocation(
                        id = 56, 
                        lat = '', 
                        lon = '', 
                        name = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                route_plans = [
                    opencarwings_client.models.route_plan.RoutePlan(
                        id = 56, 
                        name = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        start_name = '0', 
                        start_lat = '', 
                        start_lon = '', 
                        finish_name = '0', 
                        finish_lat = '', 
                        finish_lon = '', 
                        point1_name = '', 
                        point1_lat = '', 
                        point1_lon = '', 
                        point2_name = '', 
                        point2_lat = '', 
                        point2_lon = '', 
                        point3_name = '', 
                        point3_lat = '', 
                        point3_lon = '', 
                        point4_name = '', 
                        point4_lat = '', 
                        point4_lon = '', 
                        point5_name = '', 
                        point5_lat = '', 
                        point5_lon = '', )
                    ],
                command_type_display = '0',
                command_result_display = '0',
                timer_commands = [
                    opencarwings_client.models.command_timer_setting.CommandTimerSetting(
                        id = 56, 
                        command_type_display = '', 
                        last_command_result_display = '', 
                        timer_type_display = '', 
                        last_command_execution = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        enabled = True, 
                        name = '0', 
                        timer_type = 56, 
                        command_type = 56, 
                        last_command_result = 56, 
                        weekday_mon = True, 
                        weekday_tue = True, 
                        weekday_wed = True, 
                        weekday_thu = True, 
                        weekday_fri = True, 
                        weekday_sat = True, 
                        weekday_sun = True, 
                        time = '', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                vin = '0',
                sms_config = opencarwings_client.models.sms_config.Sms config(),
                owner = 56,
        )
        """

    def testCar(self):
        """Test Car"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
