# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vehicle_health_info import VehicleHealthInfo

class TestVehicleHealthInfo(unittest.TestCase):
    """VehicleHealthInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VehicleHealthInfo:
        """Test VehicleHealthInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VehicleHealthInfo`
        """
        model = VehicleHealthInfo()
        if include_optional:
            return VehicleHealthInfo(
                id = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                dtc_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                dtc_short = openapi_client.models.dtc_short.Dtc short(),
                dtc_long = openapi_client.models.dtc_long.Dtc long(),
                tpms_light = True,
                tpms_fr = -2147483648,
                tpms_fl = -2147483648,
                tpms_rr = -2147483648,
                tpms_rl = -2147483648,
                maintenance_alert = True,
                mileage = 1.337
            )
        else:
            return VehicleHealthInfo(
        )
        """

    def testVehicleHealthInfo(self):
        """Test VehicleHealthInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
