# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.account_detail import AccountDetail

class TestAccountDetail(unittest.TestCase):
    """AccountDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountDetail:
        """Test AccountDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountDetail`
        """
        model = AccountDetail()
        if include_optional:
            return AccountDetail(
                is_2fa_enabled = True,
                is_command_pin_set = True,
                timezone = '0',
                email_notifications = True,
                username = '20',
                email = '',
                units_imperial = True,
                last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AccountDetail(
                username = '20',
        )
        """

    def testAccountDetail(self):
        """Test AccountDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
