# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.models.jwt_token_login import JWTTokenLogin

class TestJWTTokenLogin(unittest.TestCase):
    """JWTTokenLogin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JWTTokenLogin:
        """Test JWTTokenLogin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JWTTokenLogin`
        """
        model = JWTTokenLogin()
        if include_optional:
            return JWTTokenLogin(
                refresh = '0',
                access = '0',
                user_id = 56,
                username = ''
            )
        else:
            return JWTTokenLogin(
                refresh = '0',
        )
        """

    def testJWTTokenLogin(self):
        """Test JWTTokenLogin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
