# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.api.alerts_api import AlertsApi


class TestAlertsApi(unittest.IsolatedAsyncioTestCase):
    """AlertsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AlertsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_alerts_read(self) -> None:
        """Test case for api_alerts_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
