# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opencarwings_client.api.cars_api import CarsApi


class TestCarsApi(unittest.IsolatedAsyncioTestCase):
    """CarsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CarsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_car_delete(self) -> None:
        """Test case for api_car_delete

        """
        pass

    async def test_api_car_list(self) -> None:
        """Test case for api_car_list

        """
        pass

    async def test_api_car_partial_update(self) -> None:
        """Test case for api_car_partial_update

        """
        pass

    async def test_api_car_read(self) -> None:
        """Test case for api_car_read

        """
        pass

    async def test_api_car_timers_create(self) -> None:
        """Test case for api_car_timers_create

        """
        pass

    async def test_api_car_timers_delete(self) -> None:
        """Test case for api_car_timers_delete

        """
        pass

    async def test_api_car_timers_list(self) -> None:
        """Test case for api_car_timers_list

        """
        pass

    async def test_api_car_timers_partial_update(self) -> None:
        """Test case for api_car_timers_partial_update

        """
        pass

    async def test_api_car_timers_read(self) -> None:
        """Test case for api_car_timers_read

        """
        pass

    async def test_api_car_timers_update(self) -> None:
        """Test case for api_car_timers_update

        """
        pass

    async def test_api_car_update(self) -> None:
        """Test case for api_car_update

        """
        pass

    async def test_api_command_create(self) -> None:
        """Test case for api_command_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
