# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.route_plan import RoutePlan

class TestRoutePlan(unittest.TestCase):
    """RoutePlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoutePlan:
        """Test RoutePlan
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoutePlan`
        """
        model = RoutePlan()
        if include_optional:
            return RoutePlan(
                id = 56,
                name = '0',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_name = '0',
                start_lat = '',
                start_lon = '',
                finish_name = '0',
                finish_lat = '',
                finish_lon = '',
                point1_name = '',
                point1_lat = '',
                point1_lon = '',
                point2_name = '',
                point2_lat = '',
                point2_lon = '',
                point3_name = '',
                point3_lat = '',
                point3_lon = '',
                point4_name = '',
                point4_lat = '',
                point4_lon = '',
                point5_name = '',
                point5_lat = '',
                point5_lon = ''
            )
        else:
            return RoutePlan(
                name = '0',
                start_name = '0',
                start_lat = '',
                start_lon = '',
                finish_name = '0',
                finish_lat = '',
                finish_lon = '',
        )
        """

    def testRoutePlan(self):
        """Test RoutePlan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
