# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.car_serializer_list import CarSerializerList

class TestCarSerializerList(unittest.TestCase):
    """CarSerializerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CarSerializerList:
        """Test CarSerializerList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CarSerializerList`
        """
        model = CarSerializerList()
        if include_optional:
            return CarSerializerList(
                vin = '0',
                last_connection = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                nickname = '0',
                ev_info = openapi_client.models.ev_info.EVInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    range_acon = -2147483648, 
                    range_acoff = -2147483648, 
                    plugged_in = True, 
                    charging = True, 
                    charge_finish = True, 
                    quick_charging = True, 
                    ac_status = True, 
                    charge_bars = -2147483648, 
                    car_running = True, 
                    car_gear = 56, 
                    eco_mode = True, 
                    soh = -2147483648, 
                    soc = 1.337, 
                    soc_display = 1.337, 
                    wh_content = 1.337, 
                    cap_bars = -2147483648, 
                    gids = -2147483648, 
                    counter = -2147483648, 
                    max_gids = -2147483648, 
                    full_chg_time = -2147483648, 
                    limit_chg_time = -2147483648, 
                    obc_6kw = -2147483648, 
                    param21 = -2147483648, 
                    cabin_temp = 1.337, 
                    force_soc_display = True, 
                    obc_6kw_avail = True, 
                    batt_heater_avail = True, 
                    batt_heater_status = True, ),
                location = openapi_client.models.location_info.LocationInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    lat = '', 
                    lon = '', 
                    home = True, ),
                carrier = '0',
                signal_level = -2147483648,
                tcu_type = 'continental2012'
            )
        else:
            return CarSerializerList(
                vin = '0',
                ev_info = openapi_client.models.ev_info.EVInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    range_acon = -2147483648, 
                    range_acoff = -2147483648, 
                    plugged_in = True, 
                    charging = True, 
                    charge_finish = True, 
                    quick_charging = True, 
                    ac_status = True, 
                    charge_bars = -2147483648, 
                    car_running = True, 
                    car_gear = 56, 
                    eco_mode = True, 
                    soh = -2147483648, 
                    soc = 1.337, 
                    soc_display = 1.337, 
                    wh_content = 1.337, 
                    cap_bars = -2147483648, 
                    gids = -2147483648, 
                    counter = -2147483648, 
                    max_gids = -2147483648, 
                    full_chg_time = -2147483648, 
                    limit_chg_time = -2147483648, 
                    obc_6kw = -2147483648, 
                    param21 = -2147483648, 
                    cabin_temp = 1.337, 
                    force_soc_display = True, 
                    obc_6kw_avail = True, 
                    batt_heater_avail = True, 
                    batt_heater_status = True, ),
                location = openapi_client.models.location_info.LocationInfo(
                    id = 56, 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    lat = '', 
                    lon = '', 
                    home = True, ),
        )
        """

    def testCarSerializerList(self):
        """Test CarSerializerList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
