# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from opencarwings_client.models.ev_info_updating import EVInfoUpdating
from opencarwings_client.models.route_plan import RoutePlan
from opencarwings_client.models.send_to_car_location import SendToCarLocation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CarUpdating(BaseModel):
    """
    CarUpdating
    """ # noqa: E501
    send_to_car_location: Optional[SendToCarLocation] = None
    send_to_car_location_all: Optional[List[SendToCarLocation]] = None
    ev_info: Optional[EVInfoUpdating] = None
    route_plans: Optional[List[RoutePlan]] = None
    favorite_channels: Optional[Dict[str, Any]] = None
    custom_channels: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["send_to_car_location", "send_to_car_location_all", "ev_info", "route_plans", "favorite_channels", "custom_channels"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CarUpdating from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of send_to_car_location
        if self.send_to_car_location:
            _dict['send_to_car_location'] = self.send_to_car_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in send_to_car_location_all (list)
        _items = []
        if self.send_to_car_location_all:
            for _item_send_to_car_location_all in self.send_to_car_location_all:
                _items.append(_item_send_to_car_location_all.to_dict() if _item_send_to_car_location_all is not None else None)
            _dict['send_to_car_location_all'] = _items
        # override the default output from pydantic by calling `to_dict()` of ev_info
        if self.ev_info:
            _dict['ev_info'] = self.ev_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in route_plans (list)
        _items = []
        if self.route_plans:
            for _item_route_plans in self.route_plans:
                _items.append(_item_route_plans.to_dict() if _item_route_plans is not None else None)
            _dict['route_plans'] = _items
        # set to None if send_to_car_location_all (nullable) is None
        # and model_fields_set contains the field
        if self.send_to_car_location_all is None and "send_to_car_location_all" in self.model_fields_set:
            _dict['send_to_car_location_all'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CarUpdating from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "send_to_car_location": SendToCarLocation.from_dict(obj["send_to_car_location"]) if obj.get("send_to_car_location") is not None else None,
            "send_to_car_location_all": [SendToCarLocation.from_dict(_item) for _item in obj["send_to_car_location_all"]] if obj.get("send_to_car_location_all") is not None else None,
            "ev_info": EVInfoUpdating.from_dict(obj["ev_info"]) if obj.get("ev_info") is not None else None,
            "route_plans": [RoutePlan.from_dict(_item) for _item in obj["route_plans"]] if obj.get("route_plans") is not None else None,
            "favorite_channels": obj.get("favorite_channels"),
            "custom_channels": obj.get("custom_channels")
        })
        return _obj


