# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opencarwings_client.models.ev_info import EVInfo
from opencarwings_client.models.location_info import LocationInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CarSerializerList(BaseModel):
    """
    CarSerializerList
    """ # noqa: E501
    vin: Annotated[str, Field(min_length=1, strict=True, max_length=18)]
    last_connection: Optional[datetime] = None
    nickname: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    ev_info: EVInfo
    location: LocationInfo
    carrier: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    signal_level: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    tcu_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["vin", "last_connection", "nickname", "ev_info", "location", "carrier", "signal_level", "tcu_type"]

    @field_validator('tcu_type')
    def tcu_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['continental2012', 'ficosa2016']):
            raise ValueError("must be one of enum values ('continental2012', 'ficosa2016')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CarSerializerList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "last_connection",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ev_info
        if self.ev_info:
            _dict['ev_info'] = self.ev_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # set to None if carrier (nullable) is None
        # and model_fields_set contains the field
        if self.carrier is None and "carrier" in self.model_fields_set:
            _dict['carrier'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CarSerializerList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vin": obj.get("vin"),
            "last_connection": obj.get("last_connection"),
            "nickname": obj.get("nickname"),
            "ev_info": EVInfo.from_dict(obj["ev_info"]) if obj.get("ev_info") is not None else None,
            "location": LocationInfo.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "carrier": obj.get("carrier"),
            "signal_level": obj.get("signal_level"),
            "tcu_type": obj.get("tcu_type")
        })
        return _obj


