# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CommandTimerSetting(BaseModel):
    """
    CommandTimerSetting
    """ # noqa: E501
    id: Optional[StrictInt] = None
    command_type_display: Optional[StrictStr] = None
    last_command_result_display: Optional[StrictStr] = None
    timer_type_display: Optional[StrictStr] = None
    last_command_execution: Optional[datetime] = None
    enabled: Optional[StrictBool] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=32)]
    timer_type: Optional[StrictInt] = None
    command_type: Optional[StrictInt] = None
    last_command_result: Optional[StrictInt] = None
    weekday_mon: Optional[StrictBool] = None
    weekday_tue: Optional[StrictBool] = None
    weekday_wed: Optional[StrictBool] = None
    weekday_thu: Optional[StrictBool] = None
    weekday_fri: Optional[StrictBool] = None
    weekday_sat: Optional[StrictBool] = None
    weekday_sun: Optional[StrictBool] = None
    time: StrictStr
    var_date: Optional[date] = Field(default=None, alias="date")
    __properties: ClassVar[List[str]] = ["id", "command_type_display", "last_command_result_display", "timer_type_display", "last_command_execution", "enabled", "name", "timer_type", "command_type", "last_command_result", "weekday_mon", "weekday_tue", "weekday_wed", "weekday_thu", "weekday_fri", "weekday_sat", "weekday_sun", "time", "date"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommandTimerSetting from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "last_command_execution",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommandTimerSetting from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "command_type_display": obj.get("command_type_display"),
            "last_command_result_display": obj.get("last_command_result_display"),
            "timer_type_display": obj.get("timer_type_display"),
            "last_command_execution": obj.get("last_command_execution"),
            "enabled": obj.get("enabled"),
            "name": obj.get("name"),
            "timer_type": obj.get("timer_type"),
            "command_type": obj.get("command_type"),
            "last_command_result": obj.get("last_command_result"),
            "weekday_mon": obj.get("weekday_mon"),
            "weekday_tue": obj.get("weekday_tue"),
            "weekday_wed": obj.get("weekday_wed"),
            "weekday_thu": obj.get("weekday_thu"),
            "weekday_fri": obj.get("weekday_fri"),
            "weekday_sat": obj.get("weekday_sat"),
            "weekday_sun": obj.get("weekday_sun"),
            "time": obj.get("time"),
            "date": obj.get("date")
        })
        return _obj


