# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PinChange(BaseModel):
    """
    PinChange
    """ # noqa: E501
    otp_code: Optional[Annotated[str, Field(strict=True, max_length=6)]] = None
    old_pin: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=4)]] = None
    new_pin: Annotated[str, Field(min_length=1, strict=True, max_length=4)]
    new_pin_confirm: Annotated[str, Field(min_length=1, strict=True, max_length=4)]
    __properties: ClassVar[List[str]] = ["otp_code", "old_pin", "new_pin", "new_pin_confirm"]

    @field_validator('otp_code', mode="before")
    def otp_code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[0-9]{6}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{6}$/")
        return value

    @field_validator('old_pin', mode="before")
    def old_pin_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}$/")
        return value

    @field_validator('new_pin', mode="before")
    def new_pin_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}$/")
        return value

    @field_validator('new_pin_confirm', mode="before")
    def new_pin_confirm_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{4}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PinChange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PinChange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "otp_code": obj.get("otp_code"),
            "old_pin": obj.get("old_pin"),
            "new_pin": obj.get("new_pin"),
            "new_pin_confirm": obj.get("new_pin_confirm")
        })
        return _obj


