# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TCUConfiguration(BaseModel):
    """
    TCUConfiguration
    """ # noqa: E501
    id: Optional[StrictInt] = None
    last_updated: Optional[datetime] = None
    dial_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    apn: Optional[Annotated[str, Field(strict=True, max_length=48)]] = None
    apn_user: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    apn_password: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    dns1: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    dns2: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    server_url: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    proxy_url: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    connection_type: Optional[Annotated[str, Field(strict=True, max_length=3)]] = None
    ficosa_config: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "last_updated", "dial_code", "apn", "apn_user", "apn_password", "dns1", "dns2", "server_url", "proxy_url", "connection_type", "ficosa_config"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TCUConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "last_updated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if dial_code (nullable) is None
        # and model_fields_set contains the field
        if self.dial_code is None and "dial_code" in self.model_fields_set:
            _dict['dial_code'] = None

        # set to None if apn (nullable) is None
        # and model_fields_set contains the field
        if self.apn is None and "apn" in self.model_fields_set:
            _dict['apn'] = None

        # set to None if apn_user (nullable) is None
        # and model_fields_set contains the field
        if self.apn_user is None and "apn_user" in self.model_fields_set:
            _dict['apn_user'] = None

        # set to None if apn_password (nullable) is None
        # and model_fields_set contains the field
        if self.apn_password is None and "apn_password" in self.model_fields_set:
            _dict['apn_password'] = None

        # set to None if dns1 (nullable) is None
        # and model_fields_set contains the field
        if self.dns1 is None and "dns1" in self.model_fields_set:
            _dict['dns1'] = None

        # set to None if dns2 (nullable) is None
        # and model_fields_set contains the field
        if self.dns2 is None and "dns2" in self.model_fields_set:
            _dict['dns2'] = None

        # set to None if server_url (nullable) is None
        # and model_fields_set contains the field
        if self.server_url is None and "server_url" in self.model_fields_set:
            _dict['server_url'] = None

        # set to None if proxy_url (nullable) is None
        # and model_fields_set contains the field
        if self.proxy_url is None and "proxy_url" in self.model_fields_set:
            _dict['proxy_url'] = None

        # set to None if connection_type (nullable) is None
        # and model_fields_set contains the field
        if self.connection_type is None and "connection_type" in self.model_fields_set:
            _dict['connection_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TCUConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "last_updated": obj.get("last_updated"),
            "dial_code": obj.get("dial_code"),
            "apn": obj.get("apn"),
            "apn_user": obj.get("apn_user"),
            "apn_password": obj.get("apn_password"),
            "dns1": obj.get("dns1"),
            "dns2": obj.get("dns2"),
            "server_url": obj.get("server_url"),
            "proxy_url": obj.get("proxy_url"),
            "connection_type": obj.get("connection_type"),
            "ficosa_config": obj.get("ficosa_config")
        })
        return _obj


