# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VehicleHealthInfo(BaseModel):
    """
    VehicleHealthInfo
    """ # noqa: E501
    id: Optional[StrictInt] = None
    last_updated: Optional[datetime] = None
    dtc_timestamp: Optional[datetime] = None
    dtc_short: Optional[Dict[str, Any]] = None
    dtc_long: Optional[Dict[str, Any]] = None
    tpms_light: Optional[StrictBool] = None
    tpms_fr: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    tpms_fl: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    tpms_rr: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    tpms_rl: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    maintenance_alert: Optional[StrictBool] = None
    mileage: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["id", "last_updated", "dtc_timestamp", "dtc_short", "dtc_long", "tpms_light", "tpms_fr", "tpms_fl", "tpms_rr", "tpms_rl", "maintenance_alert", "mileage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VehicleHealthInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "last_updated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if dtc_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.dtc_timestamp is None and "dtc_timestamp" in self.model_fields_set:
            _dict['dtc_timestamp'] = None

        # set to None if dtc_short (nullable) is None
        # and model_fields_set contains the field
        if self.dtc_short is None and "dtc_short" in self.model_fields_set:
            _dict['dtc_short'] = None

        # set to None if dtc_long (nullable) is None
        # and model_fields_set contains the field
        if self.dtc_long is None and "dtc_long" in self.model_fields_set:
            _dict['dtc_long'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VehicleHealthInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "last_updated": obj.get("last_updated"),
            "dtc_timestamp": obj.get("dtc_timestamp"),
            "dtc_short": obj.get("dtc_short"),
            "dtc_long": obj.get("dtc_long"),
            "tpms_light": obj.get("tpms_light"),
            "tpms_fr": obj.get("tpms_fr"),
            "tpms_fl": obj.get("tpms_fl"),
            "tpms_rr": obj.get("tpms_rr"),
            "tpms_rl": obj.get("tpms_rl"),
            "maintenance_alert": obj.get("maintenance_alert"),
            "mileage": obj.get("mileage")
        })
        return _obj


