# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountDetail(BaseModel):
    """
    AccountDetail
    """ # noqa: E501
    is_2fa_enabled: Optional[StrictBool] = None
    is_command_pin_set: Optional[StrictBool] = None
    timezone: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = None
    email_notifications: Optional[StrictBool] = None
    username: Annotated[str, Field(min_length=1, strict=True, max_length=16)] = Field(description="Required. 16 characters or fewer. Letters, digits and /./-/_ only.")
    email: Optional[Annotated[str, Field(strict=True, max_length=254)]] = None
    units_imperial: Optional[StrictBool] = None
    last_login: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["is_2fa_enabled", "is_command_pin_set", "timezone", "email_notifications", "username", "email", "units_imperial", "last_login"]

    @field_validator('username', mode="before")
    def username_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Za-z0-9\-_\.]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9\-_\.]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "is_2fa_enabled",
            "is_command_pin_set",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_login (nullable) is None
        # and model_fields_set contains the field
        if self.last_login is None and "last_login" in self.model_fields_set:
            _dict['last_login'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_2fa_enabled": obj.get("is_2fa_enabled"),
            "is_command_pin_set": obj.get("is_command_pin_set"),
            "timezone": obj.get("timezone"),
            "email_notifications": obj.get("email_notifications"),
            "username": obj.get("username"),
            "email": obj.get("email"),
            "units_imperial": obj.get("units_imperial"),
            "last_login": obj.get("last_login")
        })
        return _obj


