# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.command_timer_setting import CommandTimerSetting
from openapi_client.models.ev_info import EVInfo
from openapi_client.models.location_info import LocationInfo
from openapi_client.models.route_plan import RoutePlan
from openapi_client.models.send_to_car_location import SendToCarLocation
from openapi_client.models.tcu_configuration import TCUConfiguration
from openapi_client.models.vehicle_health_info import VehicleHealthInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Car(BaseModel):
    """
    Car
    """ # noqa: E501
    id: Optional[StrictInt] = None
    tcu_configuration: TCUConfiguration
    location: LocationInfo
    ev_info: EVInfo
    veh_health: Optional[VehicleHealthInfo] = None
    send_to_car_location_all: List[SendToCarLocation]
    send_to_car_location: Optional[SendToCarLocation] = None
    route_plans: List[RoutePlan]
    command_type_display: Annotated[str, Field(min_length=1, strict=True)]
    command_result_display: Annotated[str, Field(min_length=1, strict=True)]
    timer_commands: List[CommandTimerSetting]
    command_request_time: Optional[datetime] = None
    last_connection: Optional[datetime] = None
    supported_commands: Optional[List[StrictInt]] = None
    sensitive_commands: Optional[List[StrictInt]] = None
    command_pin_enforced: Optional[StrictBool] = None
    vin: Annotated[str, Field(min_length=1, strict=True, max_length=18)]
    nickname: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    sms_config: Dict[str, Any]
    color: Optional[StrictStr] = None
    vehicle_code1: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    vehicle_code2: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    vehicle_code3: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    vehicle_code4: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    tcu_model: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = None
    tcu_serial: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = None
    iccid: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=32)]] = None
    tcu_ver: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    tcu_user: Optional[Annotated[str, Field(strict=True, max_length=16)]] = None
    tcu_pass: Optional[Annotated[str, Field(strict=True, max_length=16)]] = None
    disable_auth: Optional[StrictBool] = None
    periodic_refresh: Optional[StrictInt] = None
    periodic_refresh_running: Optional[StrictInt] = None
    command_id: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    command_result: Optional[StrictInt] = None
    command_requested: Optional[StrictBool] = None
    command_payload: Optional[Dict[str, Any]] = None
    command_type: Optional[StrictInt] = None
    carrier: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    signal_level: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    odometer: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    navi_version: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    map_version: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    tcu_version: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    favorite_channels: Optional[Dict[str, Any]] = None
    custom_channels: Optional[Dict[str, Any]] = None
    hmac_key: Optional[Annotated[str, Field(strict=True, max_length=32)]] = None
    tcu_type: Optional[StrictStr] = None
    owner: StrictInt
    __properties: ClassVar[List[str]] = ["id", "tcu_configuration", "location", "ev_info", "veh_health", "send_to_car_location_all", "send_to_car_location", "route_plans", "command_type_display", "command_result_display", "timer_commands", "command_request_time", "last_connection", "supported_commands", "sensitive_commands", "command_pin_enforced", "vin", "nickname", "sms_config", "color", "vehicle_code1", "vehicle_code2", "vehicle_code3", "vehicle_code4", "tcu_model", "tcu_serial", "iccid", "tcu_ver", "tcu_user", "tcu_pass", "disable_auth", "periodic_refresh", "periodic_refresh_running", "command_id", "command_result", "command_requested", "command_payload", "command_type", "carrier", "signal_level", "odometer", "navi_version", "map_version", "tcu_version", "favorite_channels", "custom_channels", "hmac_key", "tcu_type", "owner"]

    @field_validator('color')
    def color_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['l_coulisred', 'l_deepblue', 'l_forgedbronze', 'l_gunmetallic', 'l_pearlwhite', 'l2_pearlwhite', 'l2_gunmetallic', 'l2_jadefrostmetallic', 'l2_superblack', 'l2_vividblue', 'l_planetblue', 'l_superblack', 'env200_white']):
            raise ValueError("must be one of enum values ('l_coulisred', 'l_deepblue', 'l_forgedbronze', 'l_gunmetallic', 'l_pearlwhite', 'l2_pearlwhite', 'l2_gunmetallic', 'l2_jadefrostmetallic', 'l2_superblack', 'l2_vividblue', 'l_planetblue', 'l_superblack', 'env200_white')")
        return value

    @field_validator('tcu_type')
    def tcu_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['continental2012', 'ficosa2016']):
            raise ValueError("must be one of enum values ('continental2012', 'ficosa2016')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Car from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "command_request_time",
            "last_connection",
            "supported_commands",
            "sensitive_commands",
            "command_pin_enforced",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tcu_configuration
        if self.tcu_configuration:
            _dict['tcu_configuration'] = self.tcu_configuration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ev_info
        if self.ev_info:
            _dict['ev_info'] = self.ev_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of veh_health
        if self.veh_health:
            _dict['veh_health'] = self.veh_health.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in send_to_car_location_all (list)
        _items = []
        if self.send_to_car_location_all:
            for _item_send_to_car_location_all in self.send_to_car_location_all:
                _items.append(_item_send_to_car_location_all.to_dict() if _item_send_to_car_location_all is not None else None)
            _dict['send_to_car_location_all'] = _items
        # override the default output from pydantic by calling `to_dict()` of send_to_car_location
        if self.send_to_car_location:
            _dict['send_to_car_location'] = self.send_to_car_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in route_plans (list)
        _items = []
        if self.route_plans:
            for _item_route_plans in self.route_plans:
                _items.append(_item_route_plans.to_dict() if _item_route_plans is not None else None)
            _dict['route_plans'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in timer_commands (list)
        _items = []
        if self.timer_commands:
            for _item_timer_commands in self.timer_commands:
                _items.append(_item_timer_commands.to_dict() if _item_timer_commands is not None else None)
            _dict['timer_commands'] = _items
        # set to None if veh_health (nullable) is None
        # and model_fields_set contains the field
        if self.veh_health is None and "veh_health" in self.model_fields_set:
            _dict['veh_health'] = None

        # set to None if tcu_model (nullable) is None
        # and model_fields_set contains the field
        if self.tcu_model is None and "tcu_model" in self.model_fields_set:
            _dict['tcu_model'] = None

        # set to None if tcu_serial (nullable) is None
        # and model_fields_set contains the field
        if self.tcu_serial is None and "tcu_serial" in self.model_fields_set:
            _dict['tcu_serial'] = None

        # set to None if iccid (nullable) is None
        # and model_fields_set contains the field
        if self.iccid is None and "iccid" in self.model_fields_set:
            _dict['iccid'] = None

        # set to None if tcu_ver (nullable) is None
        # and model_fields_set contains the field
        if self.tcu_ver is None and "tcu_ver" in self.model_fields_set:
            _dict['tcu_ver'] = None

        # set to None if tcu_user (nullable) is None
        # and model_fields_set contains the field
        if self.tcu_user is None and "tcu_user" in self.model_fields_set:
            _dict['tcu_user'] = None

        # set to None if tcu_pass (nullable) is None
        # and model_fields_set contains the field
        if self.tcu_pass is None and "tcu_pass" in self.model_fields_set:
            _dict['tcu_pass'] = None

        # set to None if command_payload (nullable) is None
        # and model_fields_set contains the field
        if self.command_payload is None and "command_payload" in self.model_fields_set:
            _dict['command_payload'] = None

        # set to None if carrier (nullable) is None
        # and model_fields_set contains the field
        if self.carrier is None and "carrier" in self.model_fields_set:
            _dict['carrier'] = None

        # set to None if navi_version (nullable) is None
        # and model_fields_set contains the field
        if self.navi_version is None and "navi_version" in self.model_fields_set:
            _dict['navi_version'] = None

        # set to None if map_version (nullable) is None
        # and model_fields_set contains the field
        if self.map_version is None and "map_version" in self.model_fields_set:
            _dict['map_version'] = None

        # set to None if tcu_version (nullable) is None
        # and model_fields_set contains the field
        if self.tcu_version is None and "tcu_version" in self.model_fields_set:
            _dict['tcu_version'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Car from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tcu_configuration": TCUConfiguration.from_dict(obj["tcu_configuration"]) if obj.get("tcu_configuration") is not None else None,
            "location": LocationInfo.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "ev_info": EVInfo.from_dict(obj["ev_info"]) if obj.get("ev_info") is not None else None,
            "veh_health": VehicleHealthInfo.from_dict(obj["veh_health"]) if obj.get("veh_health") is not None else None,
            "send_to_car_location_all": [SendToCarLocation.from_dict(_item) for _item in obj["send_to_car_location_all"]] if obj.get("send_to_car_location_all") is not None else None,
            "send_to_car_location": SendToCarLocation.from_dict(obj["send_to_car_location"]) if obj.get("send_to_car_location") is not None else None,
            "route_plans": [RoutePlan.from_dict(_item) for _item in obj["route_plans"]] if obj.get("route_plans") is not None else None,
            "command_type_display": obj.get("command_type_display"),
            "command_result_display": obj.get("command_result_display"),
            "timer_commands": [CommandTimerSetting.from_dict(_item) for _item in obj["timer_commands"]] if obj.get("timer_commands") is not None else None,
            "command_request_time": obj.get("command_request_time"),
            "last_connection": obj.get("last_connection"),
            "supported_commands": obj.get("supported_commands"),
            "sensitive_commands": obj.get("sensitive_commands"),
            "command_pin_enforced": obj.get("command_pin_enforced"),
            "vin": obj.get("vin"),
            "nickname": obj.get("nickname"),
            "sms_config": obj.get("sms_config"),
            "color": obj.get("color"),
            "vehicle_code1": obj.get("vehicle_code1"),
            "vehicle_code2": obj.get("vehicle_code2"),
            "vehicle_code3": obj.get("vehicle_code3"),
            "vehicle_code4": obj.get("vehicle_code4"),
            "tcu_model": obj.get("tcu_model"),
            "tcu_serial": obj.get("tcu_serial"),
            "iccid": obj.get("iccid"),
            "tcu_ver": obj.get("tcu_ver"),
            "tcu_user": obj.get("tcu_user"),
            "tcu_pass": obj.get("tcu_pass"),
            "disable_auth": obj.get("disable_auth"),
            "periodic_refresh": obj.get("periodic_refresh"),
            "periodic_refresh_running": obj.get("periodic_refresh_running"),
            "command_id": obj.get("command_id"),
            "command_result": obj.get("command_result"),
            "command_requested": obj.get("command_requested"),
            "command_payload": obj.get("command_payload"),
            "command_type": obj.get("command_type"),
            "carrier": obj.get("carrier"),
            "signal_level": obj.get("signal_level"),
            "odometer": obj.get("odometer"),
            "navi_version": obj.get("navi_version"),
            "map_version": obj.get("map_version"),
            "tcu_version": obj.get("tcu_version"),
            "favorite_channels": obj.get("favorite_channels"),
            "custom_channels": obj.get("custom_channels"),
            "hmac_key": obj.get("hmac_key"),
            "tcu_type": obj.get("tcu_type"),
            "owner": obj.get("owner")
        })
        return _obj


