# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EVInfo(BaseModel):
    """
    EVInfo
    """ # noqa: E501
    id: Optional[StrictInt] = None
    last_updated: Optional[datetime] = None
    range_acon: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    range_acoff: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    plugged_in: Optional[StrictBool] = None
    charging: Optional[StrictBool] = None
    charge_finish: Optional[StrictBool] = None
    quick_charging: Optional[StrictBool] = None
    ac_status: Optional[StrictBool] = None
    charge_bars: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    car_running: Optional[StrictBool] = None
    car_gear: Optional[StrictInt] = None
    eco_mode: Optional[StrictBool] = None
    soh: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    soc: Optional[Union[StrictFloat, StrictInt]] = None
    soc_display: Optional[Union[StrictFloat, StrictInt]] = None
    wh_content: Optional[Union[StrictFloat, StrictInt]] = None
    cap_bars: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    gids: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    counter: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    max_gids: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    full_chg_time: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    limit_chg_time: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    obc_6kw: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    param21: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    cabin_temp: Optional[Union[StrictFloat, StrictInt]] = None
    force_soc_display: Optional[StrictBool] = None
    obc_6kw_avail: Optional[StrictBool] = None
    batt_heater_avail: Optional[StrictBool] = None
    batt_heater_status: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "last_updated", "range_acon", "range_acoff", "plugged_in", "charging", "charge_finish", "quick_charging", "ac_status", "charge_bars", "car_running", "car_gear", "eco_mode", "soh", "soc", "soc_display", "wh_content", "cap_bars", "gids", "counter", "max_gids", "full_chg_time", "limit_chg_time", "obc_6kw", "param21", "cabin_temp", "force_soc_display", "obc_6kw_avail", "batt_heater_avail", "batt_heater_status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EVInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "last_updated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if range_acon (nullable) is None
        # and model_fields_set contains the field
        if self.range_acon is None and "range_acon" in self.model_fields_set:
            _dict['range_acon'] = None

        # set to None if range_acoff (nullable) is None
        # and model_fields_set contains the field
        if self.range_acoff is None and "range_acoff" in self.model_fields_set:
            _dict['range_acoff'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EVInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "last_updated": obj.get("last_updated"),
            "range_acon": obj.get("range_acon"),
            "range_acoff": obj.get("range_acoff"),
            "plugged_in": obj.get("plugged_in"),
            "charging": obj.get("charging"),
            "charge_finish": obj.get("charge_finish"),
            "quick_charging": obj.get("quick_charging"),
            "ac_status": obj.get("ac_status"),
            "charge_bars": obj.get("charge_bars"),
            "car_running": obj.get("car_running"),
            "car_gear": obj.get("car_gear"),
            "eco_mode": obj.get("eco_mode"),
            "soh": obj.get("soh"),
            "soc": obj.get("soc"),
            "soc_display": obj.get("soc_display"),
            "wh_content": obj.get("wh_content"),
            "cap_bars": obj.get("cap_bars"),
            "gids": obj.get("gids"),
            "counter": obj.get("counter"),
            "max_gids": obj.get("max_gids"),
            "full_chg_time": obj.get("full_chg_time"),
            "limit_chg_time": obj.get("limit_chg_time"),
            "obc_6kw": obj.get("obc_6kw"),
            "param21": obj.get("param21"),
            "cabin_temp": obj.get("cabin_temp"),
            "force_soc_display": obj.get("force_soc_display"),
            "obc_6kw_avail": obj.get("obc_6kw_avail"),
            "batt_heater_avail": obj.get("batt_heater_avail"),
            "batt_heater_status": obj.get("batt_heater_status")
        })
        return _obj


