# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RoutePlan(BaseModel):
    """
    RoutePlan
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=31)]
    created_at: Optional[datetime] = None
    start_name: Annotated[str, Field(min_length=1, strict=True, max_length=30)]
    start_lat: StrictStr
    start_lon: StrictStr
    finish_name: Annotated[str, Field(min_length=1, strict=True, max_length=30)]
    finish_lat: StrictStr
    finish_lon: StrictStr
    point1_name: Optional[Annotated[str, Field(strict=True, max_length=30)]] = None
    point1_lat: Optional[StrictStr] = None
    point1_lon: Optional[StrictStr] = None
    point2_name: Optional[Annotated[str, Field(strict=True, max_length=30)]] = None
    point2_lat: Optional[StrictStr] = None
    point2_lon: Optional[StrictStr] = None
    point3_name: Optional[Annotated[str, Field(strict=True, max_length=30)]] = None
    point3_lat: Optional[StrictStr] = None
    point3_lon: Optional[StrictStr] = None
    point4_name: Optional[Annotated[str, Field(strict=True, max_length=30)]] = None
    point4_lat: Optional[StrictStr] = None
    point4_lon: Optional[StrictStr] = None
    point5_name: Optional[Annotated[str, Field(strict=True, max_length=30)]] = None
    point5_lat: Optional[StrictStr] = None
    point5_lon: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "name", "created_at", "start_name", "start_lat", "start_lon", "finish_name", "finish_lat", "finish_lon", "point1_name", "point1_lat", "point1_lon", "point2_name", "point2_lat", "point2_lon", "point3_name", "point3_lat", "point3_lon", "point4_name", "point4_lat", "point4_lon", "point5_name", "point5_lat", "point5_lon"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RoutePlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if point1_name (nullable) is None
        # and model_fields_set contains the field
        if self.point1_name is None and "point1_name" in self.model_fields_set:
            _dict['point1_name'] = None

        # set to None if point1_lat (nullable) is None
        # and model_fields_set contains the field
        if self.point1_lat is None and "point1_lat" in self.model_fields_set:
            _dict['point1_lat'] = None

        # set to None if point1_lon (nullable) is None
        # and model_fields_set contains the field
        if self.point1_lon is None and "point1_lon" in self.model_fields_set:
            _dict['point1_lon'] = None

        # set to None if point2_name (nullable) is None
        # and model_fields_set contains the field
        if self.point2_name is None and "point2_name" in self.model_fields_set:
            _dict['point2_name'] = None

        # set to None if point2_lat (nullable) is None
        # and model_fields_set contains the field
        if self.point2_lat is None and "point2_lat" in self.model_fields_set:
            _dict['point2_lat'] = None

        # set to None if point2_lon (nullable) is None
        # and model_fields_set contains the field
        if self.point2_lon is None and "point2_lon" in self.model_fields_set:
            _dict['point2_lon'] = None

        # set to None if point3_name (nullable) is None
        # and model_fields_set contains the field
        if self.point3_name is None and "point3_name" in self.model_fields_set:
            _dict['point3_name'] = None

        # set to None if point3_lat (nullable) is None
        # and model_fields_set contains the field
        if self.point3_lat is None and "point3_lat" in self.model_fields_set:
            _dict['point3_lat'] = None

        # set to None if point3_lon (nullable) is None
        # and model_fields_set contains the field
        if self.point3_lon is None and "point3_lon" in self.model_fields_set:
            _dict['point3_lon'] = None

        # set to None if point4_name (nullable) is None
        # and model_fields_set contains the field
        if self.point4_name is None and "point4_name" in self.model_fields_set:
            _dict['point4_name'] = None

        # set to None if point4_lat (nullable) is None
        # and model_fields_set contains the field
        if self.point4_lat is None and "point4_lat" in self.model_fields_set:
            _dict['point4_lat'] = None

        # set to None if point4_lon (nullable) is None
        # and model_fields_set contains the field
        if self.point4_lon is None and "point4_lon" in self.model_fields_set:
            _dict['point4_lon'] = None

        # set to None if point5_name (nullable) is None
        # and model_fields_set contains the field
        if self.point5_name is None and "point5_name" in self.model_fields_set:
            _dict['point5_name'] = None

        # set to None if point5_lat (nullable) is None
        # and model_fields_set contains the field
        if self.point5_lat is None and "point5_lat" in self.model_fields_set:
            _dict['point5_lat'] = None

        # set to None if point5_lon (nullable) is None
        # and model_fields_set contains the field
        if self.point5_lon is None and "point5_lon" in self.model_fields_set:
            _dict['point5_lon'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RoutePlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "created_at": obj.get("created_at"),
            "start_name": obj.get("start_name"),
            "start_lat": obj.get("start_lat"),
            "start_lon": obj.get("start_lon"),
            "finish_name": obj.get("finish_name"),
            "finish_lat": obj.get("finish_lat"),
            "finish_lon": obj.get("finish_lon"),
            "point1_name": obj.get("point1_name"),
            "point1_lat": obj.get("point1_lat"),
            "point1_lon": obj.get("point1_lon"),
            "point2_name": obj.get("point2_name"),
            "point2_lat": obj.get("point2_lat"),
            "point2_lon": obj.get("point2_lon"),
            "point3_name": obj.get("point3_name"),
            "point3_lat": obj.get("point3_lat"),
            "point3_lon": obj.get("point3_lon"),
            "point4_name": obj.get("point4_name"),
            "point4_lat": obj.get("point4_lat"),
            "point4_lon": obj.get("point4_lon"),
            "point5_name": obj.get("point5_name"),
            "point5_lat": obj.get("point5_lat"),
            "point5_lon": obj.get("point5_lon")
        })
        return _obj


