# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TokenMetadata(BaseModel):
    """
    TokenMetadata
    """ # noqa: E501
    device_type: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    device_os: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    app_version: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    push_notification_key: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    user_agent: Optional[StrictStr] = None
    last_used_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["device_type", "device_os", "app_version", "push_notification_key", "user_agent", "last_used_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "last_used_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "device_type": obj.get("device_type"),
            "device_os": obj.get("device_os"),
            "app_version": obj.get("app_version"),
            "push_notification_key": obj.get("push_notification_key"),
            "user_agent": obj.get("user_agent"),
            "last_used_at": obj.get("last_used_at")
        })
        return _obj


