# coding: utf-8

# flake8: noqa

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountApi",
    "AlertsApi",
    "ApiApi",
    "CarsApi",
    "MaplinkApi",
    "TokenApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIError",
    "AccountDetail",
    "AlertHistoryFull",
    "ApiCommandCreateRequest",
    "Car",
    "CarSerializerList",
    "CarUpdating",
    "CommandError",
    "CommandResponse",
    "CommandTimerSetting",
    "EVInfo",
    "EVInfoUpdating",
    "JWTTokenLogin",
    "JWTTokenObtainPair",
    "LocationInfo",
    "MapLinkResolvedLocation",
    "MapLinkResolverInput",
    "MapLinkResolverResponse",
    "PinChange",
    "RoutePlan",
    "SendToCarLocation",
    "TCUConfiguration",
    "TokenBlacklist",
    "TokenMetadata",
    "TokenMetadataUpdate",
    "TokenRefresh",
    "VehicleHealthInfo",
]

# import apis into sdk package
from opencarwings_client.api.account_api import AccountApi as AccountApi
from opencarwings_client.api.alerts_api import AlertsApi as AlertsApi
from opencarwings_client.api.api_api import ApiApi as ApiApi
from opencarwings_client.api.cars_api import CarsApi as CarsApi
from opencarwings_client.api.maplink_api import MaplinkApi as MaplinkApi
from opencarwings_client.api.token_api import TokenApi as TokenApi

# import ApiClient
from opencarwings_client.api_response import ApiResponse as ApiResponse
from opencarwings_client.api_client import ApiClient as ApiClient
from opencarwings_client.configuration import Configuration as Configuration
from opencarwings_client.exceptions import OpenApiException as OpenApiException
from opencarwings_client.exceptions import ApiTypeError as ApiTypeError
from opencarwings_client.exceptions import ApiValueError as ApiValueError
from opencarwings_client.exceptions import ApiKeyError as ApiKeyError
from opencarwings_client.exceptions import ApiAttributeError as ApiAttributeError
from opencarwings_client.exceptions import ApiException as ApiException

# import models into sdk package
from opencarwings_client.models.api_error import APIError as APIError
from opencarwings_client.models.account_detail import AccountDetail as AccountDetail
from opencarwings_client.models.alert_history_full import AlertHistoryFull as AlertHistoryFull
from opencarwings_client.models.api_command_create_request import ApiCommandCreateRequest as ApiCommandCreateRequest
from opencarwings_client.models.car import Car as Car
from opencarwings_client.models.car_serializer_list import CarSerializerList as CarSerializerList
from opencarwings_client.models.car_updating import CarUpdating as CarUpdating
from opencarwings_client.models.command_error import CommandError as CommandError
from opencarwings_client.models.command_response import CommandResponse as CommandResponse
from opencarwings_client.models.command_timer_setting import CommandTimerSetting as CommandTimerSetting
from opencarwings_client.models.ev_info import EVInfo as EVInfo
from opencarwings_client.models.ev_info_updating import EVInfoUpdating as EVInfoUpdating
from opencarwings_client.models.jwt_token_login import JWTTokenLogin as JWTTokenLogin
from opencarwings_client.models.jwt_token_obtain_pair import JWTTokenObtainPair as JWTTokenObtainPair
from opencarwings_client.models.location_info import LocationInfo as LocationInfo
from opencarwings_client.models.map_link_resolved_location import MapLinkResolvedLocation as MapLinkResolvedLocation
from opencarwings_client.models.map_link_resolver_input import MapLinkResolverInput as MapLinkResolverInput
from opencarwings_client.models.map_link_resolver_response import MapLinkResolverResponse as MapLinkResolverResponse
from opencarwings_client.models.pin_change import PinChange as PinChange
from opencarwings_client.models.route_plan import RoutePlan as RoutePlan
from opencarwings_client.models.send_to_car_location import SendToCarLocation as SendToCarLocation
from opencarwings_client.models.tcu_configuration import TCUConfiguration as TCUConfiguration
from opencarwings_client.models.token_blacklist import TokenBlacklist as TokenBlacklist
from opencarwings_client.models.token_metadata import TokenMetadata as TokenMetadata
from opencarwings_client.models.token_metadata_update import TokenMetadataUpdate as TokenMetadataUpdate
from opencarwings_client.models.token_refresh import TokenRefresh as TokenRefresh
from opencarwings_client.models.vehicle_health_info import VehicleHealthInfo as VehicleHealthInfo

