name: Generate python client
on:
- push
- workflow_dispatch
permissions:
  contents: write
jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: OCW API gen
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.21
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.21
    - name: Clean old client
      run: rm -rf *
  
    - name: Generate OpenAPI document 
      run: curl "https://opencarwings.viaaq.eu/apidocs/?format=openapi" > openapi.json

    - name: Generate new client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python
        command_args: "--package-name=opencarwings_client"

    - name: Copy new client
      run: |
        cp -r python-client/* .
        cp -r python-client/.* .
        rm -rf python-client
    

    - name: Commit new client
      run: |
        echo ".github" >> .gitignore
        git config --global user.name 'APIBot'
        git config --global user.email 'developerfromjokela@users.noreply.github.com'
        git add .
        git commit -am "Update python client"
        git push
